Repository faycalBordjah/project_badger, pull requests merged in 2019-12, with the labels that each got.

#2 Fix connexion config on app file
  app.js
Labels: bug

#12 CRUD student
  api/controllers/studentController.js
  api/models/studentModel.js
  api/routes/studentRoutes.js
Labels: FEATURE

#13 student OK
  app.js
Labels: bug

#4 Feature jwt
  Dockerfile
  api/controllers/userController.js
  api/models/userModel.js
  api/routes/sessionRoutes.js
  api/routes/studentRoutes.js
  api/routes/userRoutes.js
  config/default.json
  middleware/auth.js
Labels: enhancement

#15 Improve user
  api/controllers/userController.js
  api/routes/userRoutes.js
Labels: enhancement

#11 Add postman collection
  api/controllers/sessionController.js
  api/models/sessionModel.js
  api/routes/sessionRoutes.js
  postman/Badge.postman_collection.json
Labels: documentation

#19 Update postmane collection - CRUD students
  postman/Badge.postman_collection.json
Labels: FEATURE

#18 token user route
  api/routes/userRoutes.js
Labels: enhancement

#23 Develop branch
  Dockerfile
  api/controllers/sessionController.js
  api/controllers/studentController.js
  api/controllers/userController.js
  api/models/sessionModel.js
  api/models/studentModel.js
  api/models/userModel.js
  api/routes/sessionRoutes.js
  api/routes/studentRoutes.js
  api/routes/userRoutes.js
  app.js
  config/default.json
  middleware/auth.js
  postman/Badge.postman_collection.json
Labels: FEATURE

#24 update postman collection
  postman/Badge.postman_collection.json
Labels: bug

#26 Nono
  test/test.js
Labels: FEATURE
